name: tweet bot

on:
  workflow_run:
    workflows: ['Ruby Yank']
    types: [completed]

jobs:
  tweet:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v4
      with:
        path: package-lock.json
    - uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: npm
    - uses: ethomson/send-tweet-action@v1
      with:
        status: "Hi, this is a test!"
        consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
        consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET_KEY }}
        access-token: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}
        access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}

