name: tweet bot

on:
  workflow_run:
    workflows: ['Ruby Gem']
    types: [completed]

jobs:
  tweet:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    step:
    - uses: ethomson/send-tweet-action@v1
      with:
        status: "Hi, this is a test!"
        consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
        consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET_KEY }}
        access-token: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}
        access-token-secret: ${{ secret.TWITTER_ACCESS_TOKEN_SECRET }}

